---
title: "class09"
author: "Zane"
date: "2/8/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
wisc.df <- read.csv("WisconsinCancer.csv")

```

```{r}
head(wisc.df)
```

#get rid of the last col "X" . Find out the number of patients enrolled in this study.
```{r}
#number of patients
nrow(wisc.df)
```

```{r}
ncol(wisc.df)
```

```{r}
#take col 3-32 for further analysis and take out the col "X"
wisc.data <- wisc.df[, 3:32]
head(wisc.data)
```

```{r}
#add patient ID as the row names 
rownames(wisc.data) <- wisc.df$id
head(wisc.data)
```

```{r}
#select certain col __ use the vector
wisc.df[ ,  c(2, 5, 6, 32)]
```


```{r}
#find out the number of certain types of cancer
#benign or maligant
table(wisc.df$diagnosis)
```

```{r}
#how many features are "_mean" values
colnames(wisc.data)
grep("_mean", colnames(wisc.data))
length(grep("_mean", colnames(wisc.data)))

```

```{r}
#put the selected items in a group
inds <- grep("_mean", colnames(wisc.data))
colnames(wisc.data)[inds]
```


```{r}
#calculate the means on every col use appl(), add round() as well
round(apply(wisc.data, 2, mean))

round(apply(wisc.data, 1, sd))

round(apply(wisc.data, 2, sd), 2)
```

```{r}
#perform PCA on wisc.data
wisc.pr <- prcomp(wisc.data, scale = TRUE )
summary(wisc.pr)
plot(wisc.pr)
```

```{r}
#plot wisc.pr

#a messy plot
biplot(wisc.pr)

#need to make our own plot of the PCA results
# Scatter plot observations by components 1 and 2
plot( wisc.pr$x[ ,1] , wisc.pr$x[ ,2], 
     xlab = "PC1", ylab = "PC2")
```

```{r}
#adding colors in based on the diagnosis: wisc.df$diagnosis
plot( wisc.pr$x[ ,1] , wisc.pr$x[ ,2], 
     xlab = "PC1", ylab = "PC2",
     col = wisc.df$diagnosis)
#each dot represents a patient -- a row in the data frame
## Same, scatter plot observations by components 1 and 3
plot( wisc.pr$x[ ,1] , wisc.pr$x[ ,3], 
     xlab = "PC1", ylab = "PC3",
     col = wisc.df$diagnosis)

```

```{r}
#make a scree-plot for the PCA results
#show the proportionof variance captured in each PC

variance <- wisc.pr$sdev^2
round(variance/sum(variance) *100, 2)
pve <- round(variance/sum(variance) *100, 2)
plot(pve, type = "o", xlab = "PCs")
```

```{r}
# Alternative scree plot of the same data, note data driven y-axis
#names.arg:give name of each bar, paste("PC", 1:length(pve)): form the names with the paste function
barplot(pve, ylab = "Precent of Variance Explained",
     names.arg=paste0("PC",1:length(pve)), las=2, axes = FALSE)
axis(2, at=pve, labels=round(pve,2)*100 )
```


```{r}
# Dendrogram: interpreting hierarchical clustering models
#clustering in Principla Component Space
# For hclust we need a distance matrix and we get this from our PCA resultes (i.e. wisc.pr$x)

d <- dist(wisc.pr$x[, 1:2])
hc <- hclust (d, method = "ward.D2")
plot(hc)

#cut the tree into 3 groups
grp3 <- cutree(hc, k = 3)
table(grp3)
#the results from the cutree can be used for coloring

plot(wisc.pr$x[, 1], wisc.pr$x[, 2], xlab = "PC1", ylab = "PC2", col = grp3)

#table (grp3, )
#sort the diagnosis results with logical call
diagnosis <- wisc.df$diagnosis == "M"
table (grp3, diagnosis)
```

```{r}
# Prediction of new data
#url <- "new_samples.csv"
url <- "https://tinyurl.com/new-samples-CSV"
new <- read.csv(url)
npc <- predict(wisc.pr, newdata=new)
npc


```

```{r}
#show the new data in the previous data plot

plot(wisc.pr$x[,1:2], col=wisc.df$diagnosis)
points(npc[,1], npc[,2], col=c("blue", "yellow"), pch=15, cex=3)

```

























