---
title: "Untitled"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(BiocInstaller)
library(DESeq2)

#import count data and col data

counts <- read.csv("data/airway_scaledcounts.csv", stringsAsFactors = FALSE)
metadata <-  read.csv("data/airway_metadata.csv", stringsAsFactors = FALSE)
counts
metadata
```

```{r}
#how many exps?
ncol(counts)

#check for metadata to counts correspondence
metadata$id
#[-1] means everything but #1
all(metadata$id == colnames(counts)[-1])

```

```{r}
#extract control expes (i.e. columns of the "counts" object based on the "metadata")
control.ids <- metadata$id[metadata[,"dex"] == "control"]

#use the ids to extract the control counts columns
control <- counts[, control.ids]
rownames(control) <- counts$ensgene
head(control)
```

```{r}
#for the treated groups
treated.ids <- metadata$id[metadata[,"dex"] == "treated"]
treated <- counts[, treated.ids]
rownames(treated) <- counts$ensgene
head(treated)
```

```{r}
# find the mean counts value for each gene in control exps
control.mean <- rowSums(control)/nrow(control)
head(control.mean)
```

```{r}
treated.mean <- rowSums(treated)/nrow(treated)
head(treated.mean)
```

```{r}
# combine these meancount data
meancounts <- data.frame(control.mean, treated.mean)
colSums(meancounts)
```

```{r}
#plot
plot(meancounts$control.mean, meancounts$treated.mean)
plot(log(meancounts$control.mean), log(meancounts$treated.mean))
```

```{r}
meancounts$log2fc <- log2(meancounts[,"treated.mean"]/meancounts[,"control.mean"])
head(meancounts)

#filter out zero value entry genes
#meancount
zero.vals <- which(meancounts[,1:2]==0, arr.ind=TRUE)
# define the group to be removed
to.rm <- unique(zero.vals[,1])
#remove them with [-]
mycounts <- meancounts[-to.rm,]
head(mycounts)
```

```{r}
#smaller the range of output with log function
up.ind <- mycounts$log2fc > 2
down.ind <- mycounts$log2fc < (-2)
sum(up.ind)
sum(down.ind)
```
```{r}
head(mycounts[up.ind,])
```

```{r}
# add annotation
anno <- read.csv("data/annotables_grch38.csv")
head(anno)
dim(anno)

#merge function for the annotation
mycounts.anno <- merge(x=mycounts, y= anno,
                       by.x = "row.names", by.y= "ensgene")
```


```{r}
# annotation w/ r packages
library(AnnotationDbi)
library(org.Hs.eg.db)
columns(org.Hs.eg.db)
mycounts$symbol <- mapIds(org.Hs.eg.db,
                     keys=row.names(mycounts),
                     column="SYMBOL",
                     keytype="ENSEMBL",
                     multiVals="first")
```

```{r}
#importing data
#formating for DESeq
#use the DESeqDataSetFromMatrix() function to build the required DESeqDataSet object 
dds <- DESeqDataSetFromMatrix(countData=counts, 
                              colData=metadata, 
                              design=~dex, 
                              tidy=TRUE)
dds <- DESeq(dds)
res <- results(dds)
res

```
```{r}
summary(res)
#order the result table by the smallest p value
resOrdered <- res[order(res$pvalue),]
#By default the argument alpha is set to 0.1. If the adjusted p value cutoff will be a value other than 0.1, alpha should be set to that value.
res05 <- results(dds, alpha=0.05)
summary(res05)

```


```{r}
#plotting
# get the gene ID of certain gene
i <- grep("CRISPLD2", res05$symbol)
res05[i,]
rownames(res05[i,])
#plot the variable part = "dex" column
plotCounts(dds, gene="ENSG00000103196", intgroup="dex")
```

```{r}
mycols <- rep("pink", nrow(res))
mycols[abs(res$log2FoldChange) >2] = "yellow"
subset.inds <- res$padj < 0.01 & abs(res$log2FoldChange)>2
mycols[subset.inds] <- "red"

plot(res$log2FoldChange, -log(res$padj), col=mycols)
```


































