---
title: "class05"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# 2A. Line plot
plot(weight$Age, weight$Weight, type="o", pch = 1, cex=1.5, lwd=2, ylim=c(2,10), xlab="Age(months)", ylab="Weight(kg)", main="BABYBABYBABY")
```

```{r}
# 2B bar plot
par(mar=c(2,10,2,2))
barplot(feat$Count, names.arg = feat$Feature, horiz = TRUE, las=2)
```

```{r}
# 3A color vectors
mf <- read.table("bimm143_05_rstats/male_female_counts.txt",
                 header = TRUE,
                 sep = "\t")
mfc <- read.delim("bimm143_05_rstats/male_female_counts.txt")

barplot(mf$Count, names.arg = mf$Sample, las=2, col=rainbow(10))
par(mar=c(5,1,2,3))
barplot(mf$Count, names.arg = mf$Sample, las=2, col=rainbow(10))

barplot(mf$Count, names.arg = mf$Sample, las=2, col=rainbow(ncol(mf)))
barplot(mf$Count, names.arg = mf$Sample, las=2, col="wheat")
barplot(mf$Count, names.arg = mf$Sample, las=2, col=topo.colors(nrow(mf)))
barplot(mf$Count, names.arg = mf$Sample, las=2, col=cm.colors(nrow(mf)))
```

```{r}
# 3B coloring by value
exp <- read.delim("bimm143_05_rstats/up_down_expression.txt")
nrow(exp)
table(exp$State)
plot(exp$Condition1, exp$Condition2, xlab="Expression1", ylab="Expression2", main="expression")
?plot
plot(exp$Condition1, exp$Condition2, col= topo.colors(exp$State),xlab="Expression1", ylab="Expression2", main="expression")
plot(exp$Condition1, exp$Condition2, col= exp$State,xlab="Expression1", ylab="Expression2", main="expression")
palette(c("red", "green", "blue"))
```

```{r}
# 3C dynamic
library(colorspace)
meth <- read.delim("bimm143_05_rstats/expression_methylation.txt")
densCols(meth)
nrow(meth)
plot(meth$gene.meth, meth$expression)
plot(meth$gene.meth, meth$expression, col=densCols(meth), pch=20)
pos <- meth$expression > 0
plot(meth$gene.meth[pos], meth$expression[pos])
par(mar=c(1,5,1,1))
dc <- densCols(meth$gene.meth[pos], meth$expression[pos])
plot(meth$gene.meth[pos], meth$expression[pos], col=dc, pch=20)
dcramp <- densCols(meth$gene.meth[pos], meth$expression[pos],
                   colramp = colorRampPalette(c("pink", 
                                                "orange", 
                                                "red2", 
                                                "yellow")))

plot(meth$gene.meth[pos], meth$expression[pos], col=dcramp, 
     pch=20)
```









