CLUSTAL multiple sequence alignment by MUSCLE (3.8)


DR_PAX6|        MPQKEYYNRATWESGVASMMQNKVYDICNEGHSGVNQLGGVFVNGRPLPDSTRQKIVELA
ZF_PAX6         ------------------------------------------------------------
Rab_PAX6|       ---------------------------MQNSHSGVNQLGGVFVNGRPLPDSTRQKIVELA
Rat_PAX6|       ---------------------------MQNSHSGVNQLGGVFVNGRPLPDSTRQKIVELA
Homo_PAX6       ---------------------------MQNSHSGVNQLGGVFVNGRPLPDSTRQKIVELA
Mus_PAX6        ---------------------------MQNSHSGVNQLGGVFVNGRPLPDSTRQKIVELA
                                                                            

DR_PAX6|        HSGARPCDISRILQTHADAKVQVLDNENVSNGCVSKILGRYYETGSIRPRAIGGSKPRVA
ZF_PAX6         ------------------------------------------------------------
Rab_PAX6|       HSGARPCDISRILQTHADAKVQVLDNQNVSNGCVSKILGRYYETGSIRPRAIGGSKPRVA
Rat_PAX6|       HSGARPCDISRILQ--------------VSNGCVSKILGRYYETGSIRPRAIGGSKPRVA
Homo_PAX6       HSGARPCDISRILQ--------------VSNGCVSKILGRYYETGSIRPRAIGGSKPRVA
Mus_PAX6        HSGARPCDISRILQTHADAKVQVLDNENVSNGCVSKILGRYYETGSIRPRAIGGSKPRVA
                                                                            

DR_PAX6|        TPEVVGKIAQYKRECPSIFAWEIRDRLLSEGVCTNDNIPSVSSINRVLRNLASEKQQMGA
ZF_PAX6         ----------------SIFAWEIRDRLLSEGVCTNDNIPSVSSINRVLRNLASEKQQMGA
Rab_PAX6|       TPEVVSKIAQYKRECPSIFAWEIRDRLLSEGVCTNDNIPSVSSINRVLRNLASEKQQMGA
Rat_PAX6|       TPEVVSKIAQYKRECPSIFAWEIRDRLLSEGVCTNDNIPSVSSINRVLRNLASEKQQMGA
Homo_PAX6       TPEVVSKIAQYKRECPSIFAWEIRDRLLSEGVCTNDNIPSVSSINRVLRNLASEKQQMGA
Mus_PAX6        TPEVVSKIAQYKRECPSIFAWEIRDRLLSEGVCTNDNIPSVSSINRVLRNLASEKQQMGA
                                ********************************************

DR_PAX6|        DGMYEKLRMLNGQTGTWGTRPGWYPGTSVPGQPNQDGCQQSDGGGENTNSISSNGEDSDE
ZF_PAX6         DGMYDKLRMLNGQTGTWGTRPGWYPGTSVPGQPTQDGCPQQEGGGENTNSISSNGEDSDE
Rab_PAX6|       DGMYDKLRMLNGQTGSWGTRPGWYPGTSVPGQPTQDGCQPQEGGGENTNSISSNGEDSDE
Rat_PAX6|       DGMYDKLRMLNGQTGSWGTRPGWYPGTSVPGQPTQDGCQQQEGQGENTNSISSNGEDSDE
Homo_PAX6       DGMYDKLRMLNGQTGSWGTRPGWYPGTSVPGQPTQDGCQQQEGGGENTNSISSNGEDSDE
Mus_PAX6        DGMYDKLRMLNGQTGSWGTRPGWYPGTSVPGQPTQDGCQQQEGGGENTNSISSNGEDSDE
                ****:**********:*****************.****  .:* ****************

DR_PAX6|        TQMRLQLKRKLQRNRTSFTQEQIEALEKEFERTHYPDVFARERLAAKIDLPEARIQVWFS
ZF_PAX6         AQMRLQLKRKLQRNRTSFTQEQIEALEKEFERTHYPDVFARERLAAKIDLPEARIQVWFS
Rab_PAX6|       AQMRLQLKRKLQRNRTSFTQEQIEALEKEFERTHYPDVFARERLAAKIDLPEARIQVWFS
Rat_PAX6|       AQMRLQLKRKLQRNRTSFTQEQIEALEKEFERTHYPDVFARERLAAKIDLPEARIQVWFS
Homo_PAX6       AQMRLQLKRKLQRNRTSFTQEQIEALEKEFERTHYPDVFARERLAAKIDLPEARIQVWFS
Mus_PAX6        AQMRLQLKRKLQRNRTSFTQEQIEALEKEFERTHYPDVFARERLAAKIDLPEARIQVWFS
                :***********************************************************

DR_PAX6|        NRRAKWRREEKLRNQRRQASNSSSHIPISSSFSTSVYQPIPQPTTPV-SFTSGSMLGRSD
ZF_PAX6         NRRAKWRREEKLRNQRRQASNTPSHIPISSSFSTSVYQPIPQPTTP------GSMLGRTD
Rab_PAX6|       NRRAKWRREEKLRNQRRQASNTPSHIPISSSFSTSVYQPIPQPTTPVSSFTSGSMLGRTD
Rat_PAX6|       NRRAKWRREEKLRNQRRQASNTPSHIPISSSFSTSVYQPIPQPTTPVSSFTSGSMLGRTD
Homo_PAX6       NRRAKWRREEKLRNQRRQASNTPSHIPISSSFSTSVYQPIPQPTTPVSSFTSGSMLGRTD
Mus_PAX6        NRRAKWRREEKLRNQRRQASNTPSHIPISSSFSTSVYQPIPQPTTPVSSFTSGSMLGRTD
                *********************:.***********************      ******:*

DR_PAX6|        TALTNTYSALPPMPSFTMANNLPMQ---PSQTSSYSCMLPTSPSVNGRSYDTYTPPHMQA
ZF_PAX6         TALTNTYSALPPMPSFTMANNLPMQPPVPSQTSSYSCMLPTSPSVNGRSYDTYTPPHMQT
Rab_PAX6|       TALTNTYSALPPMPSFTMANNLPMQPPVPSQTSSYSCMLPTSPSVNGRSYDTYTPPHMQT
Rat_PAX6|       TALTNTYSALPPMPSFTMANNLPMQPPVPSQTSSYSCMLPTSPSVNGRSYDTYTPPHMQT
Homo_PAX6       TALTNTYSALPPMPSFTMANNLPMQPPVPSQTSSYSCMLPTSPSVNGRSYDTYTPPHMQT
Mus_PAX6        TALTNTYSALPPMPSFTMANNLPMQPPVPSQTSSYSCMLPTSPSVNGRSYDTYTPPHMQT
                *************************   *******************************:

DR_PAX6|        HMNSQSMAASGTTSTGLISPGVSVPVQVPGSEPDMSQYWPRLQ
ZF_PAX6         HMNSQPX------------------------------------
Rab_PAX6|       HMNSQPMGTSGTTSTGLISPGVSVPVQVPGSEPDMSQYWPRLQ
Rat_PAX6|       HMNSQPMGTSGTTSTGLISPGVSVPVQVPGSEPDMSQYWPRLQ
Homo_PAX6       HMNSQPMGTSGTTSTGLISPGVSVPVQVPGSEPDMSQYWPRLQ
Mus_PAX6        HMNSQPMGTSGTTSTGLISPGVSVPVQVPGSEPDMSQYWPRLQ
                *****.                                     
